CREATE TABLE products (
  id   BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  price FLOAT NOT NULL,
  vat SMALLINT NOT NULL
);

CREATE TABLE users(
  id BIGSERIAL PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE carts(
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE cart_products(
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id),
  cart_id BIGINT NOT NULL REFERENCES carts(id),
  quantity INTEGER NOT NULL DEFAULT 1
);
